### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by eulerreich** [rkirsling/modallogic#1]
When I'm visiting your page https://rkirsling.github.io/modallogic/ chrome blocks the loading of the scripts. The specific reason cited is as below

`
Your connection to the site is encrypted, but Google Chrome has detected mixed scripting on the page. Be careful if you're entering personal information on this page. Mixed scripting can provide a loophole for someone to take over the page. This could be content third-party scripts or videos embedded on the page. If you're connected to the Internet via a public wireless network, mixed scripting is risky especially because wireless networks are easier to tamper with than wired networks.
`

I'm not quite sure what that specifically means, but perhaps you know how to fix it.

**Comment by rkirsling** [comment]
It seems this only occurs if you view the page with HTTPS -- if you go to http://rkirsling.github.io/modallogic/ everything works normally.

I actually wasn't aware that HTTPS was available for GitHub pages, so I'm curious how you ended up visiting that URL! Either way, I can make changes accordingly if this is becoming a standard practice.

**Comment by eulerreich** [comment]
I have HTTPS Everywhere enabled so it's on by default. I'd think this will
become the norm especially after Snowden.

**Comment by rkirsling** [comment]
All set! The site should now work via HTTPS as well.

**Comment by eulerreich** [comment]
Indeed! Thanks!
