### ISSUE TITLE
GitHub version of the extracted DAG Code

### ISSUE THREAD

**Issue by jakkaj** [rkirsling/modallogic#7]
Hey!

Just wondering if your extracted DAG editing code is available as a GitHub project? 

Cheers!

Jordan.

**Comment by rkirsling** [comment]
Hi @jakkaj, you can clone and fork gists like normal repos, so I think https://gist.github.com/rkirsling/5001347 should meet your needs?

**Comment by jakkaj** [comment]
Perfect!!
