### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by leonardopacheco** [rkirsling/modallogic#9]
Hello, your site was recommended in a Modal Logic course I'm currently taking and I found it really useful and interesting.

The link rkirsling.github.com/modallogic redirects to a 404 error, but the site is accessible via rkirsling.github.**io**/modallogic . This would make the program be more accesible, as people may find it hard to find the correct link and think the site does not work anymore.

**Comment by rkirsling** [comment]
Hey @leonardopacheco! Thanks for making use of this and for bringing the issue to my attention.

I guess GitHub finally stopped letting *.github.com links redirect to *.github.io; I've [updated](https://github.com/rkirsling/modallogic/commit/9d42563f35519df673abbb990acfa9744c1c210b) the links I have control over, but unfortunately I don't have an easy way to let everyone in the world know that the URL has changed... 😓

**Comment by leonardopacheco** [comment]
Thanks for the fast answer!
